/* 圖片清單（每類 16 張、共 96 張）
 * 想換成免費圖庫照片（Unsplash / Pixabay / Pexels）：
 * 下載後放進 images/ 資料夾，把 src 改成檔名即可。建議正方形、至少 800x800。
 * 目前使用的是自製插圖（CC0，可自由使用）。 */
/* 首頁的分類（名稱統一四個字）。圖片用 cat 對應；'all' 代表全部 */
window.PUZZLE_CATEGORIES = [
  { id: 'all',     icon: '🌈', name: '全部圖片' },
  { id: 'animal',  icon: '🐻', name: '可愛動物' },
  { id: 'fruit',   icon: '🍎', name: '水果甜點' },
  { id: 'nature',  icon: '🌻', name: '美麗自然' },
  { id: 'vehicle', icon: '🚗', name: '交通工具' },
  { id: 'life',    icon: '🏠', name: '日常生活' },
  { id: 'festival',icon: '🎉', name: '節慶慶典' }
];

window.PUZZLE_IMAGES = [
  /* animal */
  { id: 'cat', cat: 'animal', name: '貓咪', src: 'images/cat.svg', credit: '自製插圖 CC0' },
  { id: 'dog', cat: 'animal', name: '小狗', src: 'images/dog.svg', credit: '自製插圖 CC0' },
  { id: 'rabbit', cat: 'animal', name: '兔子', src: 'images/rabbit.svg', credit: '自製插圖 CC0' },
  { id: 'fish', cat: 'animal', name: '小魚', src: 'images/fish.svg', credit: '自製插圖 CC0' },
  { id: 'duck', cat: 'animal', name: '小鴨', src: 'images/duck.svg', credit: '自製插圖 CC0' },
  { id: 'butterfly', cat: 'animal', name: '蝴蝶', src: 'images/butterfly.svg', credit: '自製插圖 CC0' },
  { id: 'bear', cat: 'animal', name: '小熊', src: 'images/bear.svg', credit: '自製插圖 CC0' },
  { id: 'pig', cat: 'animal', name: '小豬', src: 'images/pig.svg', credit: '自製插圖 CC0' },
  { id: 'frog', cat: 'animal', name: '青蛙', src: 'images/frog.svg', credit: '自製插圖 CC0' },
  { id: 'penguin', cat: 'animal', name: '企鵝', src: 'images/penguin.svg', credit: '自製插圖 CC0' },
  { id: 'panda', cat: 'animal', name: '熊貓', src: 'images/panda.svg', credit: '自製插圖 CC0' },
  { id: 'lion', cat: 'animal', name: '獅子', src: 'images/lion.svg', credit: '自製插圖 CC0' },
  { id: 'turtle', cat: 'animal', name: '烏龜', src: 'images/turtle.svg', credit: '自製插圖 CC0' },
  { id: 'owl', cat: 'animal', name: '貓頭鷹', src: 'images/owl.svg', credit: '自製插圖 CC0' },
  { id: 'elephant', cat: 'animal', name: '大象', src: 'images/elephant.svg', credit: '自製插圖 CC0' },
  { id: 'bird', cat: 'animal', name: '小鳥', src: 'images/bird.svg', credit: '自製插圖 CC0' },
  /* fruit */
  { id: 'apple', cat: 'fruit', name: '蘋果', src: 'images/apple.svg', credit: '自製插圖 CC0' },
  { id: 'strawberry', cat: 'fruit', name: '草莓', src: 'images/strawberry.svg', credit: '自製插圖 CC0' },
  { id: 'banana', cat: 'fruit', name: '香蕉', src: 'images/banana.svg', credit: '自製插圖 CC0' },
  { id: 'orange', cat: 'fruit', name: '橘子', src: 'images/orange.svg', credit: '自製插圖 CC0' },
  { id: 'watermelon', cat: 'fruit', name: '西瓜', src: 'images/watermelon.svg', credit: '自製插圖 CC0' },
  { id: 'grapes', cat: 'fruit', name: '葡萄', src: 'images/grapes.svg', credit: '自製插圖 CC0' },
  { id: 'icecream', cat: 'fruit', name: '冰淇淋', src: 'images/icecream.svg', credit: '自製插圖 CC0' },
  { id: 'cherry', cat: 'fruit', name: '櫻桃', src: 'images/cherry.svg', credit: '自製插圖 CC0' },
  { id: 'lemon', cat: 'fruit', name: '檸檬', src: 'images/lemon.svg', credit: '自製插圖 CC0' },
  { id: 'pineapple', cat: 'fruit', name: '鳳梨', src: 'images/pineapple.svg', credit: '自製插圖 CC0' },
  { id: 'peach', cat: 'fruit', name: '水蜜桃', src: 'images/peach.svg', credit: '自製插圖 CC0' },
  { id: 'kiwi', cat: 'fruit', name: '奇異果', src: 'images/kiwi.svg', credit: '自製插圖 CC0' },
  { id: 'blueberry', cat: 'fruit', name: '藍莓', src: 'images/blueberry.svg', credit: '自製插圖 CC0' },
  { id: 'donut', cat: 'fruit', name: '甜甜圈', src: 'images/donut.svg', credit: '自製插圖 CC0' },
  { id: 'cupcake', cat: 'fruit', name: '杯子蛋糕', src: 'images/cupcake.svg', credit: '自製插圖 CC0' },
  { id: 'cookie', cat: 'fruit', name: '餅乾', src: 'images/cookie.svg', credit: '自製插圖 CC0' },
  /* nature */
  { id: 'flower', cat: 'nature', name: '花朵', src: 'images/flower.svg', credit: '自製插圖 CC0' },
  { id: 'sun', cat: 'nature', name: '太陽', src: 'images/sun.svg', credit: '自製插圖 CC0' },
  { id: 'rainbow', cat: 'nature', name: '彩虹', src: 'images/rainbow.svg', credit: '自製插圖 CC0' },
  { id: 'tree', cat: 'nature', name: '大樹', src: 'images/tree.svg', credit: '自製插圖 CC0' },
  { id: 'moon', cat: 'nature', name: '月亮', src: 'images/moon.svg', credit: '自製插圖 CC0' },
  { id: 'star', cat: 'nature', name: '星星', src: 'images/star.svg', credit: '自製插圖 CC0' },
  { id: 'cloud', cat: 'nature', name: '雲朵', src: 'images/cloud.svg', credit: '自製插圖 CC0' },
  { id: 'rain', cat: 'nature', name: '下雨', src: 'images/rain.svg', credit: '自製插圖 CC0' },
  { id: 'snowflake', cat: 'nature', name: '雪花', src: 'images/snowflake.svg', credit: '自製插圖 CC0' },
  { id: 'mountain', cat: 'nature', name: '高山', src: 'images/mountain.svg', credit: '自製插圖 CC0' },
  { id: 'mushroom', cat: 'nature', name: '蘑菇', src: 'images/mushroom.svg', credit: '自製插圖 CC0' },
  { id: 'cactus', cat: 'nature', name: '仙人掌', src: 'images/cactus.svg', credit: '自製插圖 CC0' },
  { id: 'mapleleaf', cat: 'nature', name: '楓葉', src: 'images/mapleleaf.svg', credit: '自製插圖 CC0' },
  { id: 'shell', cat: 'nature', name: '貝殼', src: 'images/shell.svg', credit: '自製插圖 CC0' },
  { id: 'tulip', cat: 'nature', name: '鬱金香', src: 'images/tulip.svg', credit: '自製插圖 CC0' },
  { id: 'clover', cat: 'nature', name: '幸運草', src: 'images/clover.svg', credit: '自製插圖 CC0' },
  /* vehicle */
  { id: 'car', cat: 'vehicle', name: '汽車', src: 'images/car.svg', credit: '自製插圖 CC0' },
  { id: 'boat', cat: 'vehicle', name: '帆船', src: 'images/boat.svg', credit: '自製插圖 CC0' },
  { id: 'rocket', cat: 'vehicle', name: '火箭', src: 'images/rocket.svg', credit: '自製插圖 CC0' },
  { id: 'bus', cat: 'vehicle', name: '公車', src: 'images/bus.svg', credit: '自製插圖 CC0' },
  { id: 'train', cat: 'vehicle', name: '火車', src: 'images/train.svg', credit: '自製插圖 CC0' },
  { id: 'airplane', cat: 'vehicle', name: '飛機', src: 'images/airplane.svg', credit: '自製插圖 CC0' },
  { id: 'bike', cat: 'vehicle', name: '腳踏車', src: 'images/bike.svg', credit: '自製插圖 CC0' },
  { id: 'firetruck', cat: 'vehicle', name: '消防車', src: 'images/firetruck.svg', credit: '自製插圖 CC0' },
  { id: 'police', cat: 'vehicle', name: '警車', src: 'images/police.svg', credit: '自製插圖 CC0' },
  { id: 'ambulance', cat: 'vehicle', name: '救護車', src: 'images/ambulance.svg', credit: '自製插圖 CC0' },
  { id: 'truck', cat: 'vehicle', name: '貨車', src: 'images/truck.svg', credit: '自製插圖 CC0' },
  { id: 'helicopter', cat: 'vehicle', name: '直升機', src: 'images/helicopter.svg', credit: '自製插圖 CC0' },
  { id: 'hotballoon', cat: 'vehicle', name: '熱氣球', src: 'images/hotballoon.svg', credit: '自製插圖 CC0' },
  { id: 'submarine', cat: 'vehicle', name: '潛水艇', src: 'images/submarine.svg', credit: '自製插圖 CC0' },
  { id: 'taxi', cat: 'vehicle', name: '計程車', src: 'images/taxi.svg', credit: '自製插圖 CC0' },
  { id: 'tractor', cat: 'vehicle', name: '拖拉機', src: 'images/tractor.svg', credit: '自製插圖 CC0' },
  /* life */
  { id: 'house', cat: 'life', name: '房子', src: 'images/house.svg', credit: '自製插圖 CC0' },
  { id: 'balloon', cat: 'life', name: '氣球', src: 'images/balloon.svg', credit: '自製插圖 CC0' },
  { id: 'book', cat: 'life', name: '書本', src: 'images/book.svg', credit: '自製插圖 CC0' },
  { id: 'pencil', cat: 'life', name: '鉛筆', src: 'images/pencil.svg', credit: '自製插圖 CC0' },
  { id: 'cup', cat: 'life', name: '杯子', src: 'images/cup.svg', credit: '自製插圖 CC0' },
  { id: 'hat', cat: 'life', name: '帽子', src: 'images/hat.svg', credit: '自製插圖 CC0' },
  { id: 'sock', cat: 'life', name: '襪子', src: 'images/sock.svg', credit: '自製插圖 CC0' },
  { id: 'umbrella', cat: 'life', name: '雨傘', src: 'images/umbrella.svg', credit: '自製插圖 CC0' },
  { id: 'glasses', cat: 'life', name: '眼鏡', src: 'images/glasses.svg', credit: '自製插圖 CC0' },
  { id: 'clock', cat: 'life', name: '時鐘', src: 'images/clock.svg', credit: '自製插圖 CC0' },
  { id: 'key', cat: 'life', name: '鑰匙', src: 'images/key.svg', credit: '自製插圖 CC0' },
  { id: 'bulb', cat: 'life', name: '燈泡', src: 'images/bulb.svg', credit: '自製插圖 CC0' },
  { id: 'ball', cat: 'life', name: '足球', src: 'images/ball.svg', credit: '自製插圖 CC0' },
  { id: 'blocks', cat: 'life', name: '積木', src: 'images/blocks.svg', credit: '自製插圖 CC0' },
  { id: 'gift', cat: 'life', name: '禮物', src: 'images/gift.svg', credit: '自製插圖 CC0' },
  { id: 'toothbrush', cat: 'life', name: '牙刷', src: 'images/toothbrush.svg', credit: '自製插圖 CC0' },
  /* festival */
  { id: 'xmastree', cat: 'festival', name: '聖誕樹', src: 'images/xmastree.svg', credit: '自製插圖 CC0' },
  { id: 'santa', cat: 'festival', name: '聖誕老人', src: 'images/santa.svg', credit: '自製插圖 CC0' },
  { id: 'snowman', cat: 'festival', name: '雪人', src: 'images/snowman.svg', credit: '自製插圖 CC0' },
  { id: 'gingerbread', cat: 'festival', name: '薑餅人', src: 'images/gingerbread.svg', credit: '自製插圖 CC0' },
  { id: 'birthdaycake', cat: 'festival', name: '生日蛋糕', src: 'images/birthdaycake.svg', credit: '自製插圖 CC0' },
  { id: 'fireworks', cat: 'festival', name: '煙火', src: 'images/fireworks.svg', credit: '自製插圖 CC0' },
  { id: 'redenvelope', cat: 'festival', name: '紅包', src: 'images/redenvelope.svg', credit: '自製插圖 CC0' },
  { id: 'lantern', cat: 'festival', name: '燈籠', src: 'images/lantern.svg', credit: '自製插圖 CC0' },
  { id: 'firecracker', cat: 'festival', name: '鞭炮', src: 'images/firecracker.svg', credit: '自製插圖 CC0' },
  { id: 'mooncake', cat: 'festival', name: '月餅', src: 'images/mooncake.svg', credit: '自製插圖 CC0' },
  { id: 'zongzi', cat: 'festival', name: '粽子', src: 'images/zongzi.svg', credit: '自製插圖 CC0' },
  { id: 'pumpkin', cat: 'festival', name: '南瓜燈', src: 'images/pumpkin.svg', credit: '自製插圖 CC0' },
  { id: 'ghost', cat: 'festival', name: '幽靈', src: 'images/ghost.svg', credit: '自製插圖 CC0' },
  { id: 'heart', cat: 'festival', name: '愛心', src: 'images/heart.svg', credit: '自製插圖 CC0' },
  { id: 'easteregg', cat: 'festival', name: '彩蛋', src: 'images/easteregg.svg', credit: '自製插圖 CC0' },
  { id: 'partyhat', cat: 'festival', name: '派對帽', src: 'images/partyhat.svg', credit: '自製插圖 CC0' }
];
