/* 圖片清單（每類 16 張、共 256 張）
 * 想換成免費圖庫照片（Unsplash / Pixabay / Pexels）：
 * 下載後放進 images/ 資料夾，把 src 改成檔名即可。
 * 新增圖片：seq 填目前最大序號 + 1，就會自動出現在「最新圖片」。建議正方形、至少 800x800。
 * 目前使用的是自製插圖（CC0，可自由使用）。 */
/* 首頁的分類（名稱統一四個字）。圖片用 cat 對應；'new' 是「最新圖片」：取 seq（加入序號）最大的 NEW_COUNT 張 */
window.PUZZLE_NEW_COUNT = 16;   // 最新圖片顯示幾張
window.PUZZLE_CATEGORIES = [
  { id: 'new',     icon: '🆕', name: '最新圖片' },
  { id: 'animal',  icon: '🐻', name: '可愛動物' },
  { id: 'fruit',   icon: '🍎', name: '水果甜點' },
  { id: 'nature',  icon: '🌻', name: '美麗自然' },
  { id: 'vehicle', icon: '🚗', name: '交通工具' },
  { id: 'life',    icon: '🏠', name: '日常生活' },
  { id: 'festival',icon: '🎉', name: '節慶慶典' },
  { id: 'learn',   icon: '🔤', name: '學習認知' },
  { id: 'story',   icon: '🏰', name: '童話故事' },
  { id: 'dino',    icon: '🦕', name: '遠古恐龍' },
  { id: 'ocean',   icon: '🐠', name: '海洋生物' },
  { id: 'job',     icon: '👷', name: '職業體驗' },
  { id: 'bug',     icon: '🐞', name: '野外昆蟲' },
  { id: 'food',    icon: '🍔', name: '好吃食物' },
  { id: 'sport',   icon: '⚽', name: '運動遊戲' },
  { id: 'music',   icon: '🎵', name: '音樂樂器' },
  { id: 'space',   icon: '🪐', name: '宇宙星球' }
];

window.PUZZLE_IMAGES = [
  /* animal */
  { id: 'cat', seq: 1, cat: 'animal', name: '貓咪', src: 'images/cat.svg', credit: '自製插圖 CC0' },
  { id: 'dog', seq: 2, cat: 'animal', name: '小狗', src: 'images/dog.svg', credit: '自製插圖 CC0' },
  { id: 'rabbit', seq: 3, cat: 'animal', name: '兔子', src: 'images/rabbit.svg', credit: '自製插圖 CC0' },
  { id: 'fish', seq: 4, cat: 'animal', name: '小魚', src: 'images/fish.svg', credit: '自製插圖 CC0' },
  { id: 'duck', seq: 5, cat: 'animal', name: '小鴨', src: 'images/duck.svg', credit: '自製插圖 CC0' },
  { id: 'butterfly', seq: 6, cat: 'animal', name: '蝴蝶', src: 'images/butterfly.svg', credit: '自製插圖 CC0' },
  { id: 'bear', seq: 13, cat: 'animal', name: '小熊', src: 'images/bear.svg', credit: '自製插圖 CC0' },
  { id: 'pig', seq: 14, cat: 'animal', name: '小豬', src: 'images/pig.svg', credit: '自製插圖 CC0' },
  { id: 'frog', seq: 15, cat: 'animal', name: '青蛙', src: 'images/frog.svg', credit: '自製插圖 CC0' },
  { id: 'penguin', seq: 16, cat: 'animal', name: '企鵝', src: 'images/penguin.svg', credit: '自製插圖 CC0' },
  { id: 'panda', seq: 17, cat: 'animal', name: '熊貓', src: 'images/panda.svg', credit: '自製插圖 CC0' },
  { id: 'lion', seq: 18, cat: 'animal', name: '獅子', src: 'images/lion.svg', credit: '自製插圖 CC0' },
  { id: 'turtle', seq: 19, cat: 'animal', name: '烏龜', src: 'images/turtle.svg', credit: '自製插圖 CC0' },
  { id: 'owl', seq: 20, cat: 'animal', name: '貓頭鷹', src: 'images/owl.svg', credit: '自製插圖 CC0' },
  { id: 'elephant', seq: 21, cat: 'animal', name: '大象', src: 'images/elephant.svg', credit: '自製插圖 CC0' },
  { id: 'bird', seq: 22, cat: 'animal', name: '小鳥', src: 'images/bird.svg', credit: '自製插圖 CC0' },
  /* fruit */
  { id: 'apple', seq: 7, cat: 'fruit', name: '蘋果', src: 'images/apple.svg', credit: '自製插圖 CC0' },
  { id: 'strawberry', seq: 8, cat: 'fruit', name: '草莓', src: 'images/strawberry.svg', credit: '自製插圖 CC0' },
  { id: 'banana', seq: 23, cat: 'fruit', name: '香蕉', src: 'images/banana.svg', credit: '自製插圖 CC0' },
  { id: 'orange', seq: 24, cat: 'fruit', name: '橘子', src: 'images/orange.svg', credit: '自製插圖 CC0' },
  { id: 'watermelon', seq: 25, cat: 'fruit', name: '西瓜', src: 'images/watermelon.svg', credit: '自製插圖 CC0' },
  { id: 'grapes', seq: 26, cat: 'fruit', name: '葡萄', src: 'images/grapes.svg', credit: '自製插圖 CC0' },
  { id: 'icecream', seq: 32, cat: 'fruit', name: '冰淇淋', src: 'images/icecream.svg', credit: '自製插圖 CC0' },
  { id: 'cherry', seq: 33, cat: 'fruit', name: '櫻桃', src: 'images/cherry.svg', credit: '自製插圖 CC0' },
  { id: 'lemon', seq: 34, cat: 'fruit', name: '檸檬', src: 'images/lemon.svg', credit: '自製插圖 CC0' },
  { id: 'pineapple', seq: 35, cat: 'fruit', name: '鳳梨', src: 'images/pineapple.svg', credit: '自製插圖 CC0' },
  { id: 'peach', seq: 36, cat: 'fruit', name: '水蜜桃', src: 'images/peach.svg', credit: '自製插圖 CC0' },
  { id: 'kiwi', seq: 37, cat: 'fruit', name: '奇異果', src: 'images/kiwi.svg', credit: '自製插圖 CC0' },
  { id: 'blueberry', seq: 38, cat: 'fruit', name: '藍莓', src: 'images/blueberry.svg', credit: '自製插圖 CC0' },
  { id: 'donut', seq: 39, cat: 'fruit', name: '甜甜圈', src: 'images/donut.svg', credit: '自製插圖 CC0' },
  { id: 'cupcake', seq: 40, cat: 'fruit', name: '杯子蛋糕', src: 'images/cupcake.svg', credit: '自製插圖 CC0' },
  { id: 'cookie', seq: 41, cat: 'fruit', name: '餅乾', src: 'images/cookie.svg', credit: '自製插圖 CC0' },
  /* nature */
  { id: 'flower', seq: 9, cat: 'nature', name: '花朵', src: 'images/flower.svg', credit: '自製插圖 CC0' },
  { id: 'sun', seq: 10, cat: 'nature', name: '太陽', src: 'images/sun.svg', credit: '自製插圖 CC0' },
  { id: 'rainbow', seq: 27, cat: 'nature', name: '彩虹', src: 'images/rainbow.svg', credit: '自製插圖 CC0' },
  { id: 'tree', seq: 28, cat: 'nature', name: '大樹', src: 'images/tree.svg', credit: '自製插圖 CC0' },
  { id: 'moon', seq: 42, cat: 'nature', name: '月亮', src: 'images/moon.svg', credit: '自製插圖 CC0' },
  { id: 'star', seq: 43, cat: 'nature', name: '星星', src: 'images/star.svg', credit: '自製插圖 CC0' },
  { id: 'cloud', seq: 44, cat: 'nature', name: '雲朵', src: 'images/cloud.svg', credit: '自製插圖 CC0' },
  { id: 'rain', seq: 45, cat: 'nature', name: '下雨', src: 'images/rain.svg', credit: '自製插圖 CC0' },
  { id: 'snowflake', seq: 46, cat: 'nature', name: '雪花', src: 'images/snowflake.svg', credit: '自製插圖 CC0' },
  { id: 'mountain', seq: 47, cat: 'nature', name: '高山', src: 'images/mountain.svg', credit: '自製插圖 CC0' },
  { id: 'mushroom', seq: 48, cat: 'nature', name: '蘑菇', src: 'images/mushroom.svg', credit: '自製插圖 CC0' },
  { id: 'cactus', seq: 49, cat: 'nature', name: '仙人掌', src: 'images/cactus.svg', credit: '自製插圖 CC0' },
  { id: 'mapleleaf', seq: 50, cat: 'nature', name: '楓葉', src: 'images/mapleleaf.svg', credit: '自製插圖 CC0' },
  { id: 'shell', seq: 51, cat: 'nature', name: '貝殼', src: 'images/shell.svg', credit: '自製插圖 CC0' },
  { id: 'tulip', seq: 52, cat: 'nature', name: '鬱金香', src: 'images/tulip.svg', credit: '自製插圖 CC0' },
  { id: 'clover', seq: 53, cat: 'nature', name: '幸運草', src: 'images/clover.svg', credit: '自製插圖 CC0' },
  /* vehicle */
  { id: 'car', seq: 11, cat: 'vehicle', name: '汽車', src: 'images/car.svg', credit: '自製插圖 CC0' },
  { id: 'boat', seq: 29, cat: 'vehicle', name: '帆船', src: 'images/boat.svg', credit: '自製插圖 CC0' },
  { id: 'rocket', seq: 31, cat: 'vehicle', name: '火箭', src: 'images/rocket.svg', credit: '自製插圖 CC0' },
  { id: 'bus', seq: 54, cat: 'vehicle', name: '公車', src: 'images/bus.svg', credit: '自製插圖 CC0' },
  { id: 'train', seq: 55, cat: 'vehicle', name: '火車', src: 'images/train.svg', credit: '自製插圖 CC0' },
  { id: 'airplane', seq: 56, cat: 'vehicle', name: '飛機', src: 'images/airplane.svg', credit: '自製插圖 CC0' },
  { id: 'bike', seq: 57, cat: 'vehicle', name: '腳踏車', src: 'images/bike.svg', credit: '自製插圖 CC0' },
  { id: 'firetruck', seq: 58, cat: 'vehicle', name: '消防車', src: 'images/firetruck.svg', credit: '自製插圖 CC0' },
  { id: 'police', seq: 59, cat: 'vehicle', name: '警車', src: 'images/police.svg', credit: '自製插圖 CC0' },
  { id: 'ambulance', seq: 60, cat: 'vehicle', name: '救護車', src: 'images/ambulance.svg', credit: '自製插圖 CC0' },
  { id: 'truck', seq: 61, cat: 'vehicle', name: '貨車', src: 'images/truck.svg', credit: '自製插圖 CC0' },
  { id: 'helicopter', seq: 62, cat: 'vehicle', name: '直升機', src: 'images/helicopter.svg', credit: '自製插圖 CC0' },
  { id: 'hotballoon', seq: 63, cat: 'vehicle', name: '熱氣球', src: 'images/hotballoon.svg', credit: '自製插圖 CC0' },
  { id: 'submarine', seq: 64, cat: 'vehicle', name: '潛水艇', src: 'images/submarine.svg', credit: '自製插圖 CC0' },
  { id: 'taxi', seq: 65, cat: 'vehicle', name: '計程車', src: 'images/taxi.svg', credit: '自製插圖 CC0' },
  { id: 'tractor', seq: 66, cat: 'vehicle', name: '拖拉機', src: 'images/tractor.svg', credit: '自製插圖 CC0' },
  /* life */
  { id: 'house', seq: 12, cat: 'life', name: '房子', src: 'images/house.svg', credit: '自製插圖 CC0' },
  { id: 'balloon', seq: 30, cat: 'life', name: '氣球', src: 'images/balloon.svg', credit: '自製插圖 CC0' },
  { id: 'book', seq: 67, cat: 'life', name: '書本', src: 'images/book.svg', credit: '自製插圖 CC0' },
  { id: 'pencil', seq: 68, cat: 'life', name: '鉛筆', src: 'images/pencil.svg', credit: '自製插圖 CC0' },
  { id: 'cup', seq: 69, cat: 'life', name: '杯子', src: 'images/cup.svg', credit: '自製插圖 CC0' },
  { id: 'hat', seq: 70, cat: 'life', name: '帽子', src: 'images/hat.svg', credit: '自製插圖 CC0' },
  { id: 'sock', seq: 71, cat: 'life', name: '襪子', src: 'images/sock.svg', credit: '自製插圖 CC0' },
  { id: 'umbrella', seq: 72, cat: 'life', name: '雨傘', src: 'images/umbrella.svg', credit: '自製插圖 CC0' },
  { id: 'glasses', seq: 73, cat: 'life', name: '眼鏡', src: 'images/glasses.svg', credit: '自製插圖 CC0' },
  { id: 'clock', seq: 74, cat: 'life', name: '時鐘', src: 'images/clock.svg', credit: '自製插圖 CC0' },
  { id: 'key', seq: 75, cat: 'life', name: '鑰匙', src: 'images/key.svg', credit: '自製插圖 CC0' },
  { id: 'bulb', seq: 76, cat: 'life', name: '燈泡', src: 'images/bulb.svg', credit: '自製插圖 CC0' },
  { id: 'ball', seq: 77, cat: 'life', name: '足球', src: 'images/ball.svg', credit: '自製插圖 CC0' },
  { id: 'blocks', seq: 78, cat: 'life', name: '積木', src: 'images/blocks.svg', credit: '自製插圖 CC0' },
  { id: 'gift', seq: 79, cat: 'life', name: '禮物', src: 'images/gift.svg', credit: '自製插圖 CC0' },
  { id: 'toothbrush', seq: 80, cat: 'life', name: '牙刷', src: 'images/toothbrush.svg', credit: '自製插圖 CC0' },
  /* festival */
  { id: 'xmastree', seq: 81, cat: 'festival', name: '聖誕樹', src: 'images/xmastree.svg', credit: '自製插圖 CC0' },
  { id: 'santa', seq: 82, cat: 'festival', name: '聖誕老人', src: 'images/santa.svg', credit: '自製插圖 CC0' },
  { id: 'snowman', seq: 83, cat: 'festival', name: '雪人', src: 'images/snowman.svg', credit: '自製插圖 CC0' },
  { id: 'gingerbread', seq: 84, cat: 'festival', name: '薑餅人', src: 'images/gingerbread.svg', credit: '自製插圖 CC0' },
  { id: 'birthdaycake', seq: 85, cat: 'festival', name: '生日蛋糕', src: 'images/birthdaycake.svg', credit: '自製插圖 CC0' },
  { id: 'fireworks', seq: 86, cat: 'festival', name: '煙火', src: 'images/fireworks.svg', credit: '自製插圖 CC0' },
  { id: 'redenvelope', seq: 87, cat: 'festival', name: '紅包', src: 'images/redenvelope.svg', credit: '自製插圖 CC0' },
  { id: 'lantern', seq: 88, cat: 'festival', name: '燈籠', src: 'images/lantern.svg', credit: '自製插圖 CC0' },
  { id: 'firecracker', seq: 89, cat: 'festival', name: '鞭炮', src: 'images/firecracker.svg', credit: '自製插圖 CC0' },
  { id: 'mooncake', seq: 90, cat: 'festival', name: '月餅', src: 'images/mooncake.svg', credit: '自製插圖 CC0' },
  { id: 'zongzi', seq: 91, cat: 'festival', name: '粽子', src: 'images/zongzi.svg', credit: '自製插圖 CC0' },
  { id: 'pumpkin', seq: 92, cat: 'festival', name: '南瓜燈', src: 'images/pumpkin.svg', credit: '自製插圖 CC0' },
  { id: 'ghost', seq: 93, cat: 'festival', name: '幽靈', src: 'images/ghost.svg', credit: '自製插圖 CC0' },
  { id: 'heart', seq: 94, cat: 'festival', name: '愛心', src: 'images/heart.svg', credit: '自製插圖 CC0' },
  { id: 'easteregg', seq: 95, cat: 'festival', name: '彩蛋', src: 'images/easteregg.svg', credit: '自製插圖 CC0' },
  { id: 'partyhat', seq: 96, cat: 'festival', name: '派對帽', src: 'images/partyhat.svg', credit: '自製插圖 CC0' },
  /* learn */
  { id: 'circle', seq: 97, cat: 'learn', name: '圓形', src: 'images/circle.svg', credit: '自製插圖 CC0' },
  { id: 'triangle', seq: 98, cat: 'learn', name: '三角形', src: 'images/triangle.svg', credit: '自製插圖 CC0' },
  { id: 'square', seq: 99, cat: 'learn', name: '正方形', src: 'images/square.svg', credit: '自製插圖 CC0' },
  { id: 'rectangle', seq: 100, cat: 'learn', name: '長方形', src: 'images/rectangle.svg', credit: '自製插圖 CC0' },
  { id: 'diamond', seq: 101, cat: 'learn', name: '菱形', src: 'images/diamond.svg', credit: '自製插圖 CC0' },
  { id: 'primary', seq: 102, cat: 'learn', name: '三原色', src: 'images/primary.svg', credit: '自製插圖 CC0' },
  { id: 'crayons', seq: 103, cat: 'learn', name: '蠟筆', src: 'images/crayons.svg', credit: '自製插圖 CC0' },
  { id: 'palette', seq: 104, cat: 'learn', name: '調色盤', src: 'images/palette.svg', credit: '自製插圖 CC0' },
  { id: 'numbers', seq: 105, cat: 'learn', name: '數字', src: 'images/numbers.svg', credit: '自製插圖 CC0' },
  { id: 'letters', seq: 106, cat: 'learn', name: '英文字母', src: 'images/letters.svg', credit: '自製插圖 CC0' },
  { id: 'bopomofo', seq: 107, cat: 'learn', name: '注音符號', src: 'images/bopomofo.svg', credit: '自製插圖 CC0' },
  { id: 'dice', seq: 108, cat: 'learn', name: '骰子', src: 'images/dice.svg', credit: '自製插圖 CC0' },
  { id: 'ruler', seq: 109, cat: 'learn', name: '尺', src: 'images/ruler.svg', credit: '自製插圖 CC0' },
  { id: 'magnifier', seq: 110, cat: 'learn', name: '放大鏡', src: 'images/magnifier.svg', credit: '自製插圖 CC0' },
  { id: 'globe', seq: 111, cat: 'learn', name: '地球儀', src: 'images/globe.svg', credit: '自製插圖 CC0' },
  { id: 'backpack', seq: 112, cat: 'learn', name: '書包', src: 'images/backpack.svg', credit: '自製插圖 CC0' },
  /* story */
  { id: 'princess', seq: 113, cat: 'story', name: '公主', src: 'images/princess.svg', credit: '自製插圖 CC0' },
  { id: 'prince', seq: 114, cat: 'story', name: '王子', src: 'images/prince.svg', credit: '自製插圖 CC0' },
  { id: 'castle', seq: 115, cat: 'story', name: '城堡', src: 'images/castle.svg', credit: '自製插圖 CC0' },
  { id: 'wand', seq: 116, cat: 'story', name: '魔法棒', src: 'images/wand.svg', credit: '自製插圖 CC0' },
  { id: 'unicorn', seq: 117, cat: 'story', name: '獨角獸', src: 'images/unicorn.svg', credit: '自製插圖 CC0' },
  { id: 'dragon', seq: 118, cat: 'story', name: '小龍', src: 'images/dragon.svg', credit: '自製插圖 CC0' },
  { id: 'redhood', seq: 119, cat: 'story', name: '小紅帽', src: 'images/redhood.svg', credit: '自製插圖 CC0' },
  { id: 'wolf', seq: 120, cat: 'story', name: '大野狼', src: 'images/wolf.svg', credit: '自製插圖 CC0' },
  { id: 'carriage', seq: 121, cat: 'story', name: '南瓜馬車', src: 'images/carriage.svg', credit: '自製插圖 CC0' },
  { id: 'slipper', seq: 122, cat: 'story', name: '玻璃鞋', src: 'images/slipper.svg', credit: '自製插圖 CC0' },
  { id: 'mirror', seq: 123, cat: 'story', name: '魔鏡', src: 'images/mirror.svg', credit: '自製插圖 CC0' },
  { id: 'mermaid', seq: 124, cat: 'story', name: '美人魚', src: 'images/mermaid.svg', credit: '自製插圖 CC0' },
  { id: 'fairy', seq: 125, cat: 'story', name: '小精靈', src: 'images/fairy.svg', credit: '自製插圖 CC0' },
  { id: 'wizard', seq: 126, cat: 'story', name: '巫師', src: 'images/wizard.svg', credit: '自製插圖 CC0' },
  { id: 'frogprince', seq: 127, cat: 'story', name: '青蛙王子', src: 'images/frogprince.svg', credit: '自製插圖 CC0' },
  { id: 'lamp', seq: 128, cat: 'story', name: '神燈', src: 'images/lamp.svg', credit: '自製插圖 CC0' },
  /* dino */
  { id: 'trex', seq: 129, cat: 'dino', name: '暴龍', src: 'images/trex.svg', credit: '自製插圖 CC0' },
  { id: 'triceratops', seq: 130, cat: 'dino', name: '三角龍', src: 'images/triceratops.svg', credit: '自製插圖 CC0' },
  { id: 'stegosaurus', seq: 131, cat: 'dino', name: '劍龍', src: 'images/stegosaurus.svg', credit: '自製插圖 CC0' },
  { id: 'brachiosaurus', seq: 132, cat: 'dino', name: '腕龍', src: 'images/brachiosaurus.svg', credit: '自製插圖 CC0' },
  { id: 'pterodactyl', seq: 133, cat: 'dino', name: '翼龍', src: 'images/pterodactyl.svg', credit: '自製插圖 CC0' },
  { id: 'raptor', seq: 134, cat: 'dino', name: '迅猛龍', src: 'images/raptor.svg', credit: '自製插圖 CC0' },
  { id: 'ankylosaurus', seq: 135, cat: 'dino', name: '甲龍', src: 'images/ankylosaurus.svg', credit: '自製插圖 CC0' },
  { id: 'parasaurolophus', seq: 136, cat: 'dino', name: '副櫛龍', src: 'images/parasaurolophus.svg', credit: '自製插圖 CC0' },
  { id: 'plesiosaur', seq: 137, cat: 'dino', name: '蛇頸龍', src: 'images/plesiosaur.svg', credit: '自製插圖 CC0' },
  { id: 'spinosaurus', seq: 138, cat: 'dino', name: '棘龍', src: 'images/spinosaurus.svg', credit: '自製插圖 CC0' },
  { id: 'dinoegg', seq: 139, cat: 'dino', name: '恐龍蛋', src: 'images/dinoegg.svg', credit: '自製插圖 CC0' },
  { id: 'footprint', seq: 140, cat: 'dino', name: '恐龍腳印', src: 'images/footprint.svg', credit: '自製插圖 CC0' },
  { id: 'fossil', seq: 141, cat: 'dino', name: '化石', src: 'images/fossil.svg', credit: '自製插圖 CC0' },
  { id: 'volcano', seq: 142, cat: 'dino', name: '火山', src: 'images/volcano.svg', credit: '自製插圖 CC0' },
  { id: 'meteor', seq: 143, cat: 'dino', name: '隕石', src: 'images/meteor.svg', credit: '自製插圖 CC0' },
  { id: 'babydino', seq: 144, cat: 'dino', name: '恐龍寶寶', src: 'images/babydino.svg', credit: '自製插圖 CC0' },
  /* ocean */
  { id: 'clownfish', seq: 145, cat: 'ocean', name: '小丑魚', src: 'images/clownfish.svg', credit: '自製插圖 CC0' },
  { id: 'pufferfish', seq: 146, cat: 'ocean', name: '河豚', src: 'images/pufferfish.svg', credit: '自製插圖 CC0' },
  { id: 'whale', seq: 147, cat: 'ocean', name: '鯨魚', src: 'images/whale.svg', credit: '自製插圖 CC0' },
  { id: 'dolphin', seq: 148, cat: 'ocean', name: '海豚', src: 'images/dolphin.svg', credit: '自製插圖 CC0' },
  { id: 'shark', seq: 149, cat: 'ocean', name: '鯊魚', src: 'images/shark.svg', credit: '自製插圖 CC0' },
  { id: 'octopus', seq: 150, cat: 'ocean', name: '章魚', src: 'images/octopus.svg', credit: '自製插圖 CC0' },
  { id: 'jellyfish', seq: 151, cat: 'ocean', name: '水母', src: 'images/jellyfish.svg', credit: '自製插圖 CC0' },
  { id: 'crab', seq: 152, cat: 'ocean', name: '螃蟹', src: 'images/crab.svg', credit: '自製插圖 CC0' },
  { id: 'seaturtle', seq: 153, cat: 'ocean', name: '海龜', src: 'images/seaturtle.svg', credit: '自製插圖 CC0' },
  { id: 'starfish', seq: 154, cat: 'ocean', name: '海星', src: 'images/starfish.svg', credit: '自製插圖 CC0' },
  { id: 'seahorse', seq: 155, cat: 'ocean', name: '海馬', src: 'images/seahorse.svg', credit: '自製插圖 CC0' },
  { id: 'seal', seq: 156, cat: 'ocean', name: '海豹', src: 'images/seal.svg', credit: '自製插圖 CC0' },
  { id: 'stingray', seq: 157, cat: 'ocean', name: '魟魚', src: 'images/stingray.svg', credit: '自製插圖 CC0' },
  { id: 'coral', seq: 158, cat: 'ocean', name: '珊瑚', src: 'images/coral.svg', credit: '自製插圖 CC0' },
  { id: 'lobster', seq: 159, cat: 'ocean', name: '龍蝦', src: 'images/lobster.svg', credit: '自製插圖 CC0' },
  { id: 'treasure', seq: 160, cat: 'ocean', name: '海底寶箱', src: 'images/treasure.svg', credit: '自製插圖 CC0' },
  /* job */
  { id: 'doctor', seq: 161, cat: 'job', name: '醫生', src: 'images/doctor.svg', credit: '自製插圖 CC0' },
  { id: 'nurse', seq: 162, cat: 'job', name: '護士', src: 'images/nurse.svg', credit: '自製插圖 CC0' },
  { id: 'policeman', seq: 163, cat: 'job', name: '警察', src: 'images/policeman.svg', credit: '自製插圖 CC0' },
  { id: 'firefighter', seq: 164, cat: 'job', name: '消防員', src: 'images/firefighter.svg', credit: '自製插圖 CC0' },
  { id: 'chef', seq: 165, cat: 'job', name: '廚師', src: 'images/chef.svg', credit: '自製插圖 CC0' },
  { id: 'teacher', seq: 166, cat: 'job', name: '老師', src: 'images/teacher.svg', credit: '自製插圖 CC0' },
  { id: 'astronaut', seq: 167, cat: 'job', name: '太空人', src: 'images/astronaut.svg', credit: '自製插圖 CC0' },
  { id: 'farmer', seq: 168, cat: 'job', name: '農夫', src: 'images/farmer.svg', credit: '自製插圖 CC0' },
  { id: 'pilot', seq: 169, cat: 'job', name: '飛行員', src: 'images/pilot.svg', credit: '自製插圖 CC0' },
  { id: 'postman', seq: 170, cat: 'job', name: '郵差', src: 'images/postman.svg', credit: '自製插圖 CC0' },
  { id: 'builder', seq: 171, cat: 'job', name: '建築工人', src: 'images/builder.svg', credit: '自製插圖 CC0' },
  { id: 'painter', seq: 172, cat: 'job', name: '畫家', src: 'images/painter.svg', credit: '自製插圖 CC0' },
  { id: 'scientist', seq: 173, cat: 'job', name: '科學家', src: 'images/scientist.svg', credit: '自製插圖 CC0' },
  { id: 'diver', seq: 174, cat: 'job', name: '潛水員', src: 'images/diver.svg', credit: '自製插圖 CC0' },
  { id: 'singer', seq: 175, cat: 'job', name: '歌手', src: 'images/singer.svg', credit: '自製插圖 CC0' },
  { id: 'photographer', seq: 176, cat: 'job', name: '攝影師', src: 'images/photographer.svg', credit: '自製插圖 CC0' },
  /* bug */
  { id: 'ladybug', seq: 177, cat: 'bug', name: '瓢蟲', src: 'images/ladybug.svg', credit: '自製插圖 CC0' },
  { id: 'bee', seq: 178, cat: 'bug', name: '蜜蜂', src: 'images/bee.svg', credit: '自製插圖 CC0' },
  { id: 'caterpillar', seq: 179, cat: 'bug', name: '毛毛蟲', src: 'images/caterpillar.svg', credit: '自製插圖 CC0' },
  { id: 'dragonfly', seq: 180, cat: 'bug', name: '蜻蜓', src: 'images/dragonfly.svg', credit: '自製插圖 CC0' },
  { id: 'ant', seq: 181, cat: 'bug', name: '螞蟻', src: 'images/ant.svg', credit: '自製插圖 CC0' },
  { id: 'snail', seq: 182, cat: 'bug', name: '蝸牛', src: 'images/snail.svg', credit: '自製插圖 CC0' },
  { id: 'grasshopper', seq: 183, cat: 'bug', name: '蚱蜢', src: 'images/grasshopper.svg', credit: '自製插圖 CC0' },
  { id: 'firefly', seq: 184, cat: 'bug', name: '螢火蟲', src: 'images/firefly.svg', credit: '自製插圖 CC0' },
  { id: 'spider', seq: 185, cat: 'bug', name: '蜘蛛', src: 'images/spider.svg', credit: '自製插圖 CC0' },
  { id: 'rhinobeetle', seq: 186, cat: 'bug', name: '獨角仙', src: 'images/rhinobeetle.svg', credit: '自製插圖 CC0' },
  { id: 'cicada', seq: 187, cat: 'bug', name: '蟬', src: 'images/cicada.svg', credit: '自製插圖 CC0' },
  { id: 'mantis', seq: 188, cat: 'bug', name: '螳螂', src: 'images/mantis.svg', credit: '自製插圖 CC0' },
  { id: 'earthworm', seq: 189, cat: 'bug', name: '蚯蚓', src: 'images/earthworm.svg', credit: '自製插圖 CC0' },
  { id: 'stagbeetle', seq: 190, cat: 'bug', name: '鍬形蟲', src: 'images/stagbeetle.svg', credit: '自製插圖 CC0' },
  { id: 'moth', seq: 191, cat: 'bug', name: '飛蛾', src: 'images/moth.svg', credit: '自製插圖 CC0' },
  { id: 'cricket', seq: 192, cat: 'bug', name: '蟋蟀', src: 'images/cricket.svg', credit: '自製插圖 CC0' },
  /* food */
  { id: 'hamburger', seq: 193, cat: 'food', name: '漢堡', src: 'images/hamburger.svg', credit: '自製插圖 CC0' },
  { id: 'pizza', seq: 194, cat: 'food', name: '披薩', src: 'images/pizza.svg', credit: '自製插圖 CC0' },
  { id: 'fries', seq: 195, cat: 'food', name: '薯條', src: 'images/fries.svg', credit: '自製插圖 CC0' },
  { id: 'hotdog', seq: 196, cat: 'food', name: '熱狗', src: 'images/hotdog.svg', credit: '自製插圖 CC0' },
  { id: 'sushi', seq: 197, cat: 'food', name: '壽司', src: 'images/sushi.svg', credit: '自製插圖 CC0' },
  { id: 'dumpling', seq: 198, cat: 'food', name: '水餃', src: 'images/dumpling.svg', credit: '自製插圖 CC0' },
  { id: 'ramen', seq: 199, cat: 'food', name: '拉麵', src: 'images/ramen.svg', credit: '自製插圖 CC0' },
  { id: 'bread', seq: 200, cat: 'food', name: '麵包', src: 'images/bread.svg', credit: '自製插圖 CC0' },
  { id: 'friedegg', seq: 201, cat: 'food', name: '荷包蛋', src: 'images/friedegg.svg', credit: '自製插圖 CC0' },
  { id: 'cheese', seq: 202, cat: 'food', name: '起司', src: 'images/cheese.svg', credit: '自製插圖 CC0' },
  { id: 'milk', seq: 203, cat: 'food', name: '牛奶', src: 'images/milk.svg', credit: '自製插圖 CC0' },
  { id: 'bubbletea', seq: 204, cat: 'food', name: '珍珠奶茶', src: 'images/bubbletea.svg', credit: '自製插圖 CC0' },
  { id: 'popcorn', seq: 205, cat: 'food', name: '爆米花', src: 'images/popcorn.svg', credit: '自製插圖 CC0' },
  { id: 'drumstick', seq: 206, cat: 'food', name: '雞腿', src: 'images/drumstick.svg', credit: '自製插圖 CC0' },
  { id: 'carrot', seq: 207, cat: 'food', name: '紅蘿蔔', src: 'images/carrot.svg', credit: '自製插圖 CC0' },
  { id: 'corn', seq: 208, cat: 'food', name: '玉米', src: 'images/corn.svg', credit: '自製插圖 CC0' },
  /* sport */
  { id: 'basketball', seq: 209, cat: 'sport', name: '籃球', src: 'images/basketball.svg', credit: '自製插圖 CC0' },
  { id: 'baseball', seq: 210, cat: 'sport', name: '棒球', src: 'images/baseball.svg', credit: '自製插圖 CC0' },
  { id: 'tennis', seq: 211, cat: 'sport', name: '網球', src: 'images/tennis.svg', credit: '自製插圖 CC0' },
  { id: 'volleyball', seq: 212, cat: 'sport', name: '排球', src: 'images/volleyball.svg', credit: '自製插圖 CC0' },
  { id: 'badminton', seq: 213, cat: 'sport', name: '羽毛球', src: 'images/badminton.svg', credit: '自製插圖 CC0' },
  { id: 'bowling', seq: 214, cat: 'sport', name: '保齡球', src: 'images/bowling.svg', credit: '自製插圖 CC0' },
  { id: 'kite', seq: 215, cat: 'sport', name: '風箏', src: 'images/kite.svg', credit: '自製插圖 CC0' },
  { id: 'slide', seq: 216, cat: 'sport', name: '溜滑梯', src: 'images/slide.svg', credit: '自製插圖 CC0' },
  { id: 'swing', seq: 217, cat: 'sport', name: '盪鞦韆', src: 'images/swing.svg', credit: '自製插圖 CC0' },
  { id: 'jumprope', seq: 218, cat: 'sport', name: '跳繩', src: 'images/jumprope.svg', credit: '自製插圖 CC0' },
  { id: 'skate', seq: 219, cat: 'sport', name: '溜冰鞋', src: 'images/skate.svg', credit: '自製插圖 CC0' },
  { id: 'skateboard', seq: 220, cat: 'sport', name: '滑板', src: 'images/skateboard.svg', credit: '自製插圖 CC0' },
  { id: 'chess', seq: 221, cat: 'sport', name: '西洋棋', src: 'images/chess.svg', credit: '自製插圖 CC0' },
  { id: 'puzzlepiece', seq: 222, cat: 'sport', name: '拼圖', src: 'images/puzzlepiece.svg', credit: '自製插圖 CC0' },
  { id: 'yoyo', seq: 223, cat: 'sport', name: '溜溜球', src: 'images/yoyo.svg', credit: '自製插圖 CC0' },
  { id: 'trophy', seq: 224, cat: 'sport', name: '獎盃', src: 'images/trophy.svg', credit: '自製插圖 CC0' },
  /* music */
  { id: 'piano', seq: 225, cat: 'music', name: '鋼琴', src: 'images/piano.svg', credit: '自製插圖 CC0' },
  { id: 'guitar', seq: 226, cat: 'music', name: '吉他', src: 'images/guitar.svg', credit: '自製插圖 CC0' },
  { id: 'violin', seq: 227, cat: 'music', name: '小提琴', src: 'images/violin.svg', credit: '自製插圖 CC0' },
  { id: 'drum', seq: 228, cat: 'music', name: '鼓', src: 'images/drum.svg', credit: '自製插圖 CC0' },
  { id: 'trumpet', seq: 229, cat: 'music', name: '小喇叭', src: 'images/trumpet.svg', credit: '自製插圖 CC0' },
  { id: 'saxophone', seq: 230, cat: 'music', name: '薩克斯風', src: 'images/saxophone.svg', credit: '自製插圖 CC0' },
  { id: 'flute', seq: 231, cat: 'music', name: '長笛', src: 'images/flute.svg', credit: '自製插圖 CC0' },
  { id: 'harp', seq: 232, cat: 'music', name: '豎琴', src: 'images/harp.svg', credit: '自製插圖 CC0' },
  { id: 'xylophone', seq: 233, cat: 'music', name: '木琴', src: 'images/xylophone.svg', credit: '自製插圖 CC0' },
  { id: 'tambourine', seq: 234, cat: 'music', name: '鈴鼓', src: 'images/tambourine.svg', credit: '自製插圖 CC0' },
  { id: 'ukulele', seq: 235, cat: 'music', name: '烏克麗麗', src: 'images/ukulele.svg', credit: '自製插圖 CC0' },
  { id: 'maracas', seq: 236, cat: 'music', name: '沙鈴', src: 'images/maracas.svg', credit: '自製插圖 CC0' },
  { id: 'harmonica', seq: 237, cat: 'music', name: '口琴', src: 'images/harmonica.svg', credit: '自製插圖 CC0' },
  { id: 'microphone', seq: 238, cat: 'music', name: '麥克風', src: 'images/microphone.svg', credit: '自製插圖 CC0' },
  { id: 'headphones', seq: 239, cat: 'music', name: '耳機', src: 'images/headphones.svg', credit: '自製插圖 CC0' },
  { id: 'musicnotes', seq: 240, cat: 'music', name: '音符', src: 'images/musicnotes.svg', credit: '自製插圖 CC0' },
  /* space */
  { id: 'mercury', seq: 241, cat: 'space', name: '水星', src: 'images/mercury.svg', credit: '自製插圖 CC0' },
  { id: 'venus', seq: 242, cat: 'space', name: '金星', src: 'images/venus.svg', credit: '自製插圖 CC0' },
  { id: 'earth', seq: 243, cat: 'space', name: '地球', src: 'images/earth.svg', credit: '自製插圖 CC0' },
  { id: 'mars', seq: 244, cat: 'space', name: '火星', src: 'images/mars.svg', credit: '自製插圖 CC0' },
  { id: 'jupiter', seq: 245, cat: 'space', name: '木星', src: 'images/jupiter.svg', credit: '自製插圖 CC0' },
  { id: 'saturn', seq: 246, cat: 'space', name: '土星', src: 'images/saturn.svg', credit: '自製插圖 CC0' },
  { id: 'uranus', seq: 247, cat: 'space', name: '天王星', src: 'images/uranus.svg', credit: '自製插圖 CC0' },
  { id: 'neptune', seq: 248, cat: 'space', name: '海王星', src: 'images/neptune.svg', credit: '自製插圖 CC0' },
  { id: 'galaxy', seq: 249, cat: 'space', name: '銀河', src: 'images/galaxy.svg', credit: '自製插圖 CC0' },
  { id: 'comet', seq: 250, cat: 'space', name: '彗星', src: 'images/comet.svg', credit: '自製插圖 CC0' },
  { id: 'alien', seq: 251, cat: 'space', name: '外星人', src: 'images/alien.svg', credit: '自製插圖 CC0' },
  { id: 'ufo', seq: 252, cat: 'space', name: '飛碟', src: 'images/ufo.svg', credit: '自製插圖 CC0' },
  { id: 'satellite', seq: 253, cat: 'space', name: '人造衛星', src: 'images/satellite.svg', credit: '自製插圖 CC0' },
  { id: 'telescope', seq: 254, cat: 'space', name: '望遠鏡', src: 'images/telescope.svg', credit: '自製插圖 CC0' },
  { id: 'constellation', seq: 255, cat: 'space', name: '星座', src: 'images/constellation.svg', credit: '自製插圖 CC0' },
  { id: 'shuttle', seq: 256, cat: 'space', name: '太空梭', src: 'images/shuttle.svg', credit: '自製插圖 CC0' }
];
